package com.sbom.publicationrecord.web;

import com.fasterxml.jackson.annotation.JsonInclude;

@JsonInclude(JsonInclude.Include.NON_NULL)
public record SbomResponse (String status,
                            String message,
                            String fileName,
                            String format,
                            String generatedAt,
                            String publicationMode,
                            String sbomSha256,
                            String commitSha,
                            String resolvedVersion,
                            String swidTagId,
                            String swidFileName,
                            String combinedSbomFileName,
                            String proofRecordFileName,
                            String doi,
                            String doiUrl,
                            String zenodoRecordId,
                            String zenodoConceptRecid,
                            String zenodoRecordUrl,
                            String doiReservedAt,
                            String doiRegisteredObservedAt,
                            String publicationManifestFileName,
                            boolean zenodoPublished,
                            String zenodoDraftUrl,
                            String publicationStage,
                            String publicationStatus,
                            String progressMessage,
                            String publicSbomUrl,
                            String publicSwidUrl,
                            String publicCombinedSbomUrl,
                            String proofRecordUrl,
                            String publicPublicationManifestUrl,
                            boolean rawSbomPublished,
                            boolean combinedArtifactPublished,
                            String privateSbomDownloadUrl,
                            String privateSbomDownloadExpiresAt,
                            Boolean privateSbomDownloadAvailable,
                            String privateSbomDownloadMessage){ }
