package com.sbom.publicationrecord.service;

import com.sbom.publicationrecord.publication.PublicationMode;
import com.sbom.publicationrecord.publication.PublicationStage;
import com.sbom.publicationrecord.publication.PublicationStatusView;

import java.nio.file.Path;
import java.time.Instant;

public record SbomResult(String fileName,
                         Path filePath,
                         String sbomSha256,
                         String commitSha,
                         String resolvedVersion,
                         Instant generatedAt,
                         PublicationMode publicationMode,
                         String swidTagId,
                         String swidFileName,
                         String combinedSbomFileName,
                         String proofRecordFileName,
                         String publicSbomUrl,
                         String publicSwidUrl,
                         String publicCombinedSbomUrl,
                         String proofRecordUrl,
                         String doi,
                         String doiUrl,
                         String zenodoRecordId,
                         String zenodoConceptRecid,
                         String zenodoRecordUrl,
                         Instant doiReservedAt,
                         Instant doiRegisteredObservedAt,
                         String publicationManifestFileName,
                         Path publicationManifestFilePath,
                         String publicPublicationManifestUrl,
                         boolean zenodoPublished,
                         String zenodoDraftUrl,
                         PublicationStage publicationStage,
                         PublicationStatusView publicationStatus,
                         String progressMessage,
                         boolean rawSbomPublished,
                         boolean combinedArtifactPublished,
                         String failureMessage,
                         String privateSbomDownloadUrl,
                         Instant privateSbomDownloadExpiresAt,
                         boolean privateSbomDownloadAvailable,
                         String privateSbomDownloadMessage) {
    public SbomResult(String fileName,
                      Path filePath,
                      String sbomSha256,
                      String commitSha,
                      String resolvedVersion,
                      Instant generatedAt,
                      PublicationMode publicationMode,
                      String swidTagId,
                      String swidFileName,
                      String combinedSbomFileName,
                      String proofRecordFileName,
                      String publicSbomUrl,
                      String publicSwidUrl,
                      String publicCombinedSbomUrl,
                      String proofRecordUrl,
                      String doi,
                      String doiUrl,
                      String zenodoRecordId,
                      String zenodoConceptRecid,
                      String zenodoRecordUrl,
                      Instant doiReservedAt,
                      Instant doiRegisteredObservedAt,
                      String publicationManifestFileName,
                      Path publicationManifestFilePath,
                      String publicPublicationManifestUrl,
                      boolean zenodoPublished,
                      String zenodoDraftUrl,
                      PublicationStage publicationStage,
                      PublicationStatusView publicationStatus,
                      String progressMessage,
                      boolean rawSbomPublished,
                      boolean combinedArtifactPublished,
                      String failureMessage) {
        this(
                fileName,
                filePath,
                sbomSha256,
                commitSha,
                resolvedVersion,
                generatedAt,
                publicationMode,
                swidTagId,
                swidFileName,
                combinedSbomFileName,
                proofRecordFileName,
                publicSbomUrl,
                publicSwidUrl,
                publicCombinedSbomUrl,
                proofRecordUrl,
                doi,
                doiUrl,
                zenodoRecordId,
                zenodoConceptRecid,
                zenodoRecordUrl,
                doiReservedAt,
                doiRegisteredObservedAt,
                publicationManifestFileName,
                publicationManifestFilePath,
                publicPublicationManifestUrl,
                zenodoPublished,
                zenodoDraftUrl,
                publicationStage,
                publicationStatus,
                progressMessage,
                rawSbomPublished,
                combinedArtifactPublished,
                failureMessage,
                null,
                null,
                false,
                null
        );
    }
}
